### ISSUE TITLE
Ugly appereance when using popular UI Frameworks

### ISSUE THREAD

**Issue by uwla** [e-anka/vue-anka-cropper#38]
When using popular UI Frameworks, such as bootstrap, usually the frameworks set some default CSS such as `box-size: border-box`, among others, which work well for the most part. As a result, the appearance of this plugin's components is messed up.

I found out, by trial, that the following settings will prevent UI frameworks from messing up with this plugin:

```css
.ankaCropper a {
    box-sizing: content-box;
}

.ankaCropper svg {
    vertical-align: unset;
}

.ankaCropper__saveButton {
    display: flex !important;
    align-items: center;
}
```

Hope this helps!
